name: Build e testes SonarCloud

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 📥 Checkout Código
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ⚙️ Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      # 📦 Restore
      - name: Restore
        run: dotnet restore ApiFinancas.sln

      # 🔧 Instala SonarScanner
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      # 🔧 Adiciona tools globais ao PATH
      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          
      # 🔍 Sonar Begin
      - name: Sonar Begin
        run: |
          dotnet sonarscanner begin \
            /k:"dmrogger_Api-Financas" \
            /o:"dmrogger" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths=**/TestResults/*.opencover.xml \
            /d:sonar.exclusions="**/bin/**,**/obj/**" \
            /d:sonar.coverage.exclusions="**/Application/DTOs/**,**/*Request.cs,**/*Response.cs,**/Infrastructure/Persistence/*Configurations.cs,**/Migrations/**,**/Program.cs"

      # 🏗️ Build
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 🧪 Test + Coverage
      - name: Test with coverage
        run: |
          dotnet test ApiFinancas.sln \
            --configuration Release \
            --no-build \
            /p:CollectCoverage=true \
            /p:CoverletOutput=./TestResults/coverage \
            /p:CoverletOutputFormat=opencover

      # 🔎 Debug
      - name: Debug coverage file
        run: |
          echo "Arquivos de coverage encontrados:"
          find . -name "*.opencover.xml"

          FILE=$(find . -name "*.opencover.xml" | head -n 1)

          if [ -z "$FILE" ]; then
            echo "Nenhum arquivo de coverage encontrado"
          else
            echo "Preview de $FILE"
            head -n 20 "$FILE"
          fi

      # 🔍 Sonar END
      - name: SonarCloud End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"