
name: Build e testes SonarCloud

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 📥 Checkout Código
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ⚙️ Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 📦 Restore
      - name: Restore
        run: dotnet restore ApiFinancas.sln

      # 🔧 Instalação SonarScanner
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      # 🔍 Sonar Begin
      - name: Sonar Begin
        run: |
          dotnet sonarscanner begin \
            /k:"dmrogger_Api-Financas" \
            /o:"dmrogger" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths=TestResults/coverage.opencover.xml
            /d:sonar.exclusions="**/bin/**,**/obj/**,**/*Dto.cs,**/*Request.cs,**/*Response.cs" \
            /d:sonar.coverage.exclusions="**/Controllers/**,**/Entities/**,**/Program.cs,**/Configurations/**,**/Migrations/**"

      # 🏗️ Build
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 🧪 Test + Coverage
      - name: Test with coverage
        run: |
          dotnet test ApiFinancas.sln \
            --configuration Release \
            --no-build \
            /p:CollectCoverage=true \
            /p:CoverletOutput=./TestResults/coverage \
            /p:CoverletOutputFormat=opencover

      # 🔎 Debug (opcional, mas MUITO útil)
      - name: Debug coverage file
        run: |
          echo "Arquivos gerados:"
          ls -R
          echo "Preview coverage:"
          head -n 20 TestResults/coverage.xml || echo "Arquivo não encontrado"

      # 🔍 Sonar END
      - name: SonarCloud End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
